### ISSUE TITLE
Tracers found in Skull Island!!

### ISSUE THREAD

**Issue by serrq** [PirateNetwork/Skull-Island#47]
Exodus allows to analyze app permissions and trackers.

Skull Island, an app focused on security and privacy, tracks my activities within the app.

Unstoppable Wallet has 0 trackers.

Please remove the tracers or I uninstall the app and my adventure with arrr ends here.

Your app need to pass the Exodus test.

https://exodus-privacy.eu.org/en/

https://github.com/Exodus-Privacy/exodus

![Screenshot_2022-10-13-08-35-34-94_4564f9a59c8d632cd637a2e468bb50ad (1)](https://user-images.githubusercontent.com/113377431/195521208-64be53d4-17c2-4d5c-aa8c-7a4f36c27dfa.jpg)

![Screenshot_2022-10-13-08-35-59-45_4564f9a59c8d632cd637a2e468bb50ad (1)](https://user-images.githubusercontent.com/113377431/195521231-06d5e5e7-f73a-45e7-b126-5388fb21235d.jpg)

![Screenshot_2022-10-13-08-39-53-23_4564f9a59c8d632cd637a2e468bb50ad (1)](https://user-images.githubusercontent.com/113377431/195521298-528322d5-ac18-4552-98db-37f4134057d7.jpg)

**Comment by kaks25** [comment]
Usa la versione Non-google, tutte le app che viene installato da play store il pacchetto di google sono pre-inserite

https://github.com/PirateNetwork/Skull-Island/releases/download/v2.1.0/Skull-Island-v2.1.0.apk

**Comment by kaks25** [comment]
you need to uninstall the app and install the github version, which app analyzer do you use?

**Comment by TheComputerGenie** [comment]
That report shows that you have not updated since 2021, you're using a version that isn't even available to the public anymore, and you're wanting something removed that was removed 6 months ago.

**Comment by kaks25** [comment]
As i said 2.0.0 its play store version thats why you see the google tracker, ask them to analyze the 2.1.0 from github

**Comment by TheComputerGenie** [comment]
Given that you already opened https://github.com/PirateNetwork/Skull-Island/issues/48 and this is an issue with a non-relevant version, I'm closing this issue.
