### ISSUE TITLE
Adding your own repo to F-droid

### ISSUE THREAD

**Issue by serrq** [PirateNetwork/Skull-Island#50]
F-droid (in its various incarnations) has become the most widely used update tool among de-googled communities.

I am asking if the Skull Island team can make their own repo available to download the wallet as an alternative to the already secure route today on GitHub.

The reason is that an app store is the most convenient way to update so many apps, and most importantly it makes life easier for those users who are not computer literate.

Despite the fact that this is not a flaw in the app, however, it is a demand on it, and the unconvenient distribution of the software may be a cause of its low uptake, which is why I ask the team to calmly analyze this proposal while hoping that such a strategy will carry over into the success that this ambitious project deserves to have.

![Screenshot_2022-10-18-13-07-34-69_bf5286d428c97f865e4b51a5afbaefcd (1)](https://user-images.githubusercontent.com/113377431/196416157-70d60846-2134-45bc-95d4-879d2e6dcd1d.jpg)

![Screenshot_2022-10-18-13-08-05-23_bf5286d428c97f865e4b51a5afbaefcd (1)](https://user-images.githubusercontent.com/113377431/196416206-7e298673-21e9-4712-b89a-883db5e3496b.jpg)

**Comment by TheComputerGenie** [comment]
https://github.com/PirateNetwork/Skull-Island/issues/9
