### ISSUE TITLE
Black screen 

### ISSUE THREAD

**Issue by serrq** [PirateNetwork/Skull-Island#52]
After entering the password correctly, this black unsolved screen appears.

What could have happened?

Skull Island 2.1.0 Android 12

![Screenshot_2022-11-06-07-10-17-42_fdbad510e6f1c2dcda777141efa6ab05 (1)](https://user-images.githubusercontent.com/113377431/200157651-2b8a42e4-a842-4735-8a8b-5b8e18c7a653.jpg)

**Comment by kaks25** [comment]
Check your internet connection

**Comment by kaks25** [comment]
check the Wallet connection permission from app settings, that black screen is when the wallet doesnt reach to the internet

**Comment by kaks25** [comment]
Try without VPN if it works then its VPN issue if doesnt then your wallet it doesnt connects to internet at all

**Comment by kaks25** [comment]
Clear the app data, uninstall the wallet and reinstall it

**Comment by kaks25** [comment]
if it doesnt again mean you should check your internet
