### ISSUE TITLE
Distribute through F-Droid

### ISSUE THREAD

**Issue by LongJohn-Silver** [PirateNetwork/Skull-Island#9]
Title, basically, it would be nice to see this application on F-Droid, it will help it to gain more popularity and it will probably also help the coin.

You could also consider publishing on IzzyOnDroid while the whole F-Droid process is accepted.

**Comment by TheComputerGenie** [comment]
That's a community and distribution choice and not an issue with the app.

**Comment by LongJohn-Silver** [comment]
Ehhh, I have done this a hundred times and it is something really common to propose distribution platforms in software. Besides, it is a problem with the app, you can be using outdated software without a self-updating mechanisms and it also makes it safer than downloading random software from any place since there requirements to upload there.

Where should I propose this otherwise anyway? This is what GitHub repositories are for...

**Comment by TheComputerGenie** [comment]
> it also makes it safer than downloading random software from any place since there requirements to upload there

https://github.com/PirateNetwork/Skull-Island/releases is the official place, it's never "random software", and the requirements to upload are exactly as strict as the team decides because the team controls who does and doesn't have upload access.
>This is what GitHub repositories are for...
